name: Set up environment
description: Installs Node.js and modules with caching.

inputs:
  token:
    description: GitHub Token
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
        cache: npm
        cache-dependency-path: package-lock.json
    - uses: actions/cache@v3
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm clean-install
