name: Set up environment
description: Installs Node.js and modules with caching.

inputs:
  token:
    description: GitHub Token
    required: true

runs:
  using: composite
  steps:
    - uses: jdx/mise-action@v2
      with:
        version: 2025.5.17
        cache: true
    - uses: actions/cache@v4
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm clean-install --include=dev
